id: P000728
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20018
  title: '྾ ༼གློག་པར༽ ཟེར་ཕྲེང་ལས་མངོན་པའི་ནད་གཞིར་ངོས་འཛིན་བྱ་ཐབས། '
  author: ''
  volumes:
    2de34ffe9eb44d6a9428c0cefd53c9c7:
      image_group_id: I1KG21763
      title: ''
      volume_number: 1
      total_pages: 184
      base_file: v001.txt
