id: ICDFE2676
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:59:23+00:00'
last_modified: '2022-06-07T13:34:52.361117+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20018
  title: '྾ ༼གློག་པར༽ ཟེར་ཕྲེང་ལས་མངོན་པའི་ནད་གཞིར་ངོས་འཛིན་བྱ་ཐབས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EADB:
      image_group_id: I1KG21763
      title: ''
      total_pages: 184
      order: 1
      base_file: EADB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
